// src/features/sign-in/ui/SignInForm.tsx
'use client';

import { Controller, useForm, type SubmitHandler } from 'react-hook-form';
import { Button, Form, InputGroup } from 'react-bootstrap';
import { zodResolver } from '@hookform/resolvers/zod';

import {
  signInRequestSchema,
  type SignInRequestDto,
} from '@/features/sign-in/schema';
import { useAppConfigStore } from '@/shared/stores';

export default function SignInForm() {
  const { isAutoSignIn, setAutoSignIn } = useAppConfigStore();

  const { control, handleSubmit } = useForm<SignInRequestDto>({
    resolver: zodResolver(signInRequestSchema),
    defaultValues: { userName: '', password: '', isAuto: isAutoSignIn },
  });

  const onSubmit: SubmitHandler<SignInRequestDto> = (data) => {
    console.log(data);
  };

  return (
    <Form onSubmit={handleSubmit(onSubmit)}>
      <Form.Group className="mb-3" controlId="signin-userId">
        <Form.Label>{'아이디'}</Form.Label>
        <InputGroup hasValidation>
          <Controller
            name="userName"
            control={control}
            render={({ field, fieldState }) => (
              <>
                <Form.Control
                  {...field}
                  type="text"
                  placeholder="아이디를 입력하세요"
                  isInvalid={!!fieldState.error}
                />
                <Form.Control.Feedback type="invalid">
                  {fieldState.error?.message}
                </Form.Control.Feedback>
              </>
            )}
          />
        </InputGroup>
      </Form.Group>

      <Form.Group className="mb-3" controlId="signin-password">
        <Form.Label>{'비밀번호'}</Form.Label>
        <InputGroup hasValidation>
          <Controller
            name="password"
            control={control}
            render={({ field, fieldState }) => (
              <>
                <Form.Control
                  {...field}
                  type="password"
                  placeholder="비밀번호를 입력하세요"
                  isInvalid={!!fieldState.error}
                />
                <Form.Control.Feedback type="invalid">
                  {fieldState.error?.message}
                </Form.Control.Feedback>
              </>
            )}
          />
        </InputGroup>
      </Form.Group>

      <Form.Group className="mb-3" controlId="signin-auto">
        <Controller
          name="isAuto"
          control={control}
          render={({ field: { value, onChange, onBlur, name, ref } }) => (
            <Form.Check
              type="checkbox"
              label="자동 로그인"
              id="signin-auto-check"
              name={name}
              ref={ref}
              onBlur={onBlur}
              checked={value}
              onChange={(e) => {
                onChange(e.target.checked);
                setAutoSignIn(e.target.checked);
              }}
            />
          )}
        />
      </Form.Group>

      <div className="d-grid gap-2 mb-3">
        <Button variant="primary" type="submit">
          {'로그인'}
        </Button>
      </div>
    </Form>
  );
}

// layers/base/app/components/views/auth/sign-in-form.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import { useAppConfigStore } from '~/stores/app';
import {
  signInRequestSchema,
  type SignInRequestDto,
} from '~~/shared/schema/auth/sign-in';

const appConfigStore = useAppConfigStore();

const { handleSubmit, errors, defineField } = useForm<SignInRequestDto>({
  validationSchema: toTypedSchema(signInRequestSchema),
  initialValues: {
    userName: '',
    password: '',
    isAuto: appConfigStore.isAutoSignIn,
  },
});

const [userName, userNameProps] = defineField('userName');
const [password, passwordProps] = defineField('password');
const [isAuto, isAutoProps] = defineField('isAuto');

watch(isAuto, (newVal) => {
  appConfigStore.setAutoSignIn(newVal);
});

const onSubmit = handleSubmit((values) => {
  alert(JSON.stringify(values));
});
</script>

<template>
  <BForm @submit="onSubmit">
    <BFormGroup
      label="아이디"
      label-for="user-name"
      class="mb-2"
      :invalid-feedback="errors.userName"
      :state="!errors.userName"
    >
      <BFormInput
        id="user-name"
        v-model="userName"
        v-bind="userNameProps"
        :state="errors.userName ? false : null"
        placeholder="아이디를 입력해주세요"
      />
    </BFormGroup>

    <BFormGroup
      label="비밀번호"
      label-for="password"
      class="mb-2"
      :invalid-feedback="errors.password"
      :state="!errors.password"
    >
      <BFormInput
        id="password"
        v-model="password"
        type="password"
        v-bind="passwordProps"
        :state="errors.password ? false : null"
        placeholder="비밀번호를 입력해주세요"
      />
    </BFormGroup>

    <BFormCheckbox
      id="is-auto"
      v-model="isAuto"
      v-bind="isAutoProps"
      class="mb-3"
    >
      자동 로그인
    </BFormCheckbox>

    <BButton type="submit" variant="primary" class="w-100 mt-2">
      로그인
    </BButton>
  </BForm>
</template>
