// src/features/auth/sign-out/ui/SignOutButton.tsx
'use client';
import { useState } from 'react';

import { useRouter } from 'next/navigation';

import { Button } from 'react-bootstrap';
import { signOutAction } from '../actions';
import { useAuthStore } from '@/entities/auth/store';

export default function SignOutButton() {
  const router = useRouter();

  const [isLoading, setLoading] = useState<boolean>(false);

  const { signOut } = useAuthStore();

  const onClick = async () => {
    setLoading(true);
    try {
      await signOutAction();
    } finally {
      signOut();
      router.replace('/sign-in');
    }
  };

  return (
    <Button
      variant="outline-light"
      type="button"
      onClick={onClick}
      disabled={isLoading}
    >
      {'로그아웃'}
    </Button>
  );
}

// layers/auth/app/components/ui/sign-out-button.vue
<script setup lang="ts">
import { useAuthStore } from '~~/layers/auth/app/stores/auth';

const isLoading = ref<boolean>(false);

const authStore = useAuthStore();

const onClick = async () => {
  isLoading.value = true;
  await $fetch('/api/auth/sign-out', {
    method: 'POST',
  });
  authStore.signOut();
  isLoading.value = false;
  return await navigateTo('/sign-in', { replace: true });
};
</script>

<template>
  <BButton
    variant="outline-light"
    type="button"
    :disabled="isLoading"
    @click="onClick"
    >로그아웃</BButton
  >
</template>
