// layers/auth/app/components/views/sign-in-form.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';

import { useAppConfigStore } from '~~/layers/base/app/stores/app';
import { useAuthStore } from '~~/layers/auth/app/stores/auth';
import {
  signInRequestSchema,
  type SignInRequestDto,
} from '~~/layers/auth/contract/schema/sign-in';

const appConfigStore = useAppConfigStore();
const authStore = useAuthStore();

const isLoading = ref<boolean>(false);
const rootError = ref<string | null>(null);

const { handleSubmit, errors, defineField } = useForm<SignInRequestDto>({
  validationSchema: toTypedSchema(signInRequestSchema),
  initialValues: {
    userName: '',
    password: '',
    isAuto: appConfigStore.isAutoSignIn,
  },
});

const [userName, userNameProps] = defineField('userName');
const [password, passwordProps] = defineField('password');
const [isAuto, isAutoProps] = defineField('isAuto');

watch(isAuto, (newVal) => {
  appConfigStore.setAutoSignIn(newVal);
});

const onSubmit = handleSubmit(async (values) => {
  rootError.value = null;
  isLoading.value = true;

  const response = await $fetch('/api/auth/sign-in', {
    method: 'POST',
    body: values,
  });

  if (response.code !== 'SU') {
    switch (response.code) {
      case 'LGE':
      case 'VE':
        rootError.value = '아이디 또는 비밀번호가 올바르지 않습니다.';
        break;

      default:
        rootError.value =
          '서버에서 문제가 발생했습니다. 잠시 후 다시 시도해주세요.';
    }

    isLoading.value = false;
    return;
  }

  authStore.signIn(response.result);

  isLoading.value = false;
  return await navigateTo('/', { replace: true });
});
</script>

<template>
  <BForm @submit="onSubmit">
    <BFormGroup
      label="아이디"
      label-for="user-name"
      class="mb-2"
      :invalid-feedback="errors.userName"
      :state="!errors.userName"
    >
      <BFormInput
        id="user-name"
        v-model="userName"
        v-bind="userNameProps"
        :state="errors.userName ? false : null"
        placeholder="아이디를 입력해주세요"
      />
    </BFormGroup>

    <BFormGroup
      label="비밀번호"
      label-for="password"
      class="mb-2"
      :invalid-feedback="errors.password"
      :state="!errors.password"
    >
      <BFormInput
        id="password"
        v-model="password"
        type="password"
        v-bind="passwordProps"
        :state="errors.password ? false : null"
        placeholder="비밀번호를 입력해주세요"
      />
    </BFormGroup>

    <BFormCheckbox
      id="is-auto"
      v-model="isAuto"
      v-bind="isAutoProps"
      class="mb-3"
    >
      자동 로그인
    </BFormCheckbox>

    <div class="d-block invalid-feedback mb-2">{{ rootError }}</div>

    <BButton
      type="submit"
      variant="primary"
      class="w-100 mt-2"
      :disabled="isLoading"
    >
      <BSpinner v-if="isLoading" small />
      로그인
    </BButton>
  </BForm>
</template>

// src/features/auth/sign-in/ui/SignInForm.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/router';
import { Controller, useForm, type SubmitHandler } from 'react-hook-form';
import { Button, Form, InputGroup } from 'react-bootstrap';
import { zodResolver } from '@hookform/resolvers/zod';

import {
  signInRequestSchema,
  type SignInRequestDto,
} from '@/features/auth/sign-in/schema';
import { useAppConfigStore } from '@/shared/stores';
import { signInAction } from '@/features/auth/sign-in/actions';

export default function SignInForm() {
  const router = useRouter();

  const [isError, setError] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');

  const { isAutoSignIn, setAutoSignIn } = useAppConfigStore();

  const { control, handleSubmit } = useForm<SignInRequestDto>({
    resolver: zodResolver(signInRequestSchema),
    defaultValues: { userName: '', password: '', isAuto: isAutoSignIn },
  });

  const onSubmit: SubmitHandler<SignInRequestDto> = async (data) => {
    setError(false);
    setErrorMessage('');

    const response = await signInAction(data);

    if (response.code !== 'SU') {
      setError(true);

      switch (response.code) {
        case 'LGE':
          setErrorMessage('아이디 또는 비밀번호가 올바르지 않습니다.');
          break;

        case 'VE':
          setErrorMessage('아이디와 비밀번호를 입력해주세요.');
          break;

        default:
          setErrorMessage(
            '서버에서 문제가 발생했습니다. 잠시 후 다시 시도해주세요.',
          );
      }

      return;
    }

    router.replace('/');
  };

  return (
    <Form onSubmit={handleSubmit(onSubmit)}>
      <Form.Group className="mb-3" controlId="signin-userId">
        <Form.Label>{'아이디'}</Form.Label>
        <InputGroup hasValidation>
          <Controller
            name="userName"
            control={control}
            render={({ field, fieldState }) => (
              <>
                <Form.Control
                  {...field}
                  type="text"
                  placeholder="아이디를 입력하세요"
                  isInvalid={!!fieldState.error}
                />
                <Form.Control.Feedback type="invalid">
                  {fieldState.error?.message}
                </Form.Control.Feedback>
              </>
            )}
          />
        </InputGroup>
      </Form.Group>

      <Form.Group className="mb-3" controlId="signin-password">
        <Form.Label>{'비밀번호'}</Form.Label>
        <InputGroup hasValidation>
          <Controller
            name="password"
            control={control}
            render={({ field, fieldState }) => (
              <>
                <Form.Control
                  {...field}
                  type="password"
                  placeholder="비밀번호를 입력하세요"
                  isInvalid={!!fieldState.error}
                />
                <Form.Control.Feedback type="invalid">
                  {fieldState.error?.message}
                </Form.Control.Feedback>
              </>
            )}
          />
        </InputGroup>
      </Form.Group>

      <Form.Group className="mb-3" controlId="signin-auto">
        <Controller
          name="isAuto"
          control={control}
          render={({ field: { value, onChange, onBlur, name, ref } }) => (
            <Form.Check
              type="checkbox"
              label="자동 로그인"
              id="signin-auto-check"
              name={name}
              ref={ref}
              onBlur={onBlur}
              checked={value}
              onChange={(e) => {
                onChange(e.target.checked);
                setAutoSignIn(e.target.checked);
              }}
            />
          )}
        />
      </Form.Group>

      <Form.Group className="mb-3">
        {isError && (
          <div className="invalid-feedback" style={{ display: 'block' }}>
            {errorMessage}
          </div>
        )}
      </Form.Group>

      <div className="d-grid gap-2 mb-3">
        <Button variant="primary" type="submit">
          {'로그인'}
        </Button>
      </div>
    </Form>
  );
}
